import { sqliteTable, check, integer, text, uniqueIndex, index, unique } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

// Source of truth for the DB schema. Generated by `drizzle-kit pull` against the live v41
// database, then hand-corrected: drizzle-kit 0.31.10's SQLite check-constraint introspection
// attaches every CHECK in the database to every table (and truncates multi-clause SQL text),
// so each check() below was manually reassigned to its real owning table and its SQL text
// restored to match the original `CREATE TABLE` (verified against `sqlite_master`). See
// docs/DATABASE.md for the migration workflow — never hand-edit `src/db/migrations/`, only
// this file, then run `drizzle-kit generate`.

// Retained (not dropped) purely so an existing DB's legacy hash-verification table isn't
// destroyed by a future `generate` — no longer written to; see src/db/migrations.ts.
export const schemaMigrations = sqliteTable("schema_migrations", {
  version: integer().primaryKey(),
  hash: text().notNull(),
});

export const birthdays = sqliteTable(
  "birthdays",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    date: text().notNull(),
    mention: text().notNull(),
    userId: text("user_id"),
    name: text(),
    source: text().default("list").notNull(),
  },
  (table) => [uniqueIndex("idx_birthdays_user").on(table.userId), index("idx_birthdays_date").on(table.date)],
);

export const settings = sqliteTable(
  "settings",
  {
    id: integer().primaryKey(),
    birthdayTemplate: text("birthday_template").notNull(),
    firstBirthdayMessageId: text("first_birthday_message_id"),
    birthdayListChannelId: text("birthday_list_channel_id"),
    birthdayListMessageId: text("birthday_list_message_id"),
    birthdayCron: text("birthday_cron").default("0 0 * * *").notNull(),
    leaveNotificationsEnabled: integer("leave_notifications_enabled").default(1).notNull(),
    birthdayModChannelId: text("birthday_mod_channel_id"),
    birthdaySelfRegistrationEnabled: integer("birthday_self_registration_enabled").default(1).notNull(),
    birthdayBotManagesAnchor: integer("birthday_bot_manages_anchor").default(0).notNull(),
    birthdayAnchorTemplate: text("birthday_anchor_template").default("**{month}**\n{entries}").notNull(),
    fontMap: text("font_map"),
    birthdayAnchorUseFont: integer("birthday_anchor_use_font").default(0).notNull(),
    birthdayAnnouncementUseFont: integer("birthday_announcement_use_font").default(0).notNull(),
    registerGateRoleId: text("register_gate_role_id"),
    registrationTierRoleId: text("registration_tier_role_id"),
    birthdayAnchorIntro: text("birthday_anchor_intro"),
    rulesAcceptedUseDiscordScreening: integer("rules_accepted_use_discord_screening").default(0).notNull(),
    registerChannelId: text("register_channel_id"),
    roleSelectionChannelId: text("role_selection_channel_id"),
    registerConfirmationTemplate: text("register_confirmation_template")
      .default("Danke {name}! Du wirst in Kürze registriert. Bis dahin kannst du dir schon in {roleChannel} deine Rollen aussuchen.")
      .notNull(),
    registerNicknameUseFont: integer("register_nickname_use_font").default(1).notNull(),
    registerAutoComplete: integer("register_auto_complete").default(0).notNull(),
    autoRegisterConfirmationTemplate: text("auto_register_confirmation_template")
      .default(
        "Willkommen {name}! Du bist jetzt vollständig registriert. Schau dir gerne schon in {roleChannel} deine Rollen an. Dieser Thread schließt sich in einer Stunde automatisch.",
      )
      .notNull(),
    apolloEventChannelId: text("apollo_event_channel_id"),
    eventVoiceChannelId: text("event_voice_channel_id"),
    registerNicknameEmoji: text("register_nickname_emoji").default("💙").notNull(),
    registerConfirmationUseFont: integer("register_confirmation_use_font").default(0).notNull(),
    autoRegisterConfirmationUseFont: integer("auto_register_confirmation_use_font").default(0).notNull(),
    dashboardModeratorRoleId: text("dashboard_moderator_role_id"),
    eventChannelCleanupEnabled: integer("event_channel_cleanup_enabled").default(0).notNull(),
    eventChannelCleanupDelayHours: integer("event_channel_cleanup_delay_hours").default(24).notNull(),
    tempVoiceCategoryId: text("temp_voice_category_id"),
    tempVoiceMaxAmount: integer("temp_voice_max_amount").default(15).notNull(),
    tempVoiceNameFormat: text("temp_voice_name_format").default("Gruppe {n}").notNull(),
  },
  () => [check("settings_id_singleton", sql`id = 1`)],
);

export const commandSettings = sqliteTable("command_settings", {
  name: text().primaryKey(),
  enabled: integer().default(1).notNull(),
  guildOnly: integer("guild_only").default(1).notNull(),
  permissionGate: text("permission_gate"),
});

export const reactionRolePanels = sqliteTable(
  "reaction_role_panels",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    channelId: text("channel_id").notNull(),
    messageId: text("message_id"),
    managed: integer().default(1).notNull(),
    mode: text().default("toggle").notNull(),
    removeReaction: integer("remove_reaction").default(0).notNull(),
    title: text(),
    description: text(),
    createdAt: text("created_at").notNull(),
    selectionType: text("selection_type").default("reactions").notNull(),
    messageType: text("message_type").default("embed").notNull(),
    allowMultiple: integer("allow_multiple").default(0).notNull(),
    removable: integer().default(1).notNull(),
    allowedRoleIds: text("allowed_role_ids"),
    sent: integer().default(0).notNull(),
    name: text().default("").notNull(),
    useFont: integer("use_font").default(0).notNull(),
  },
  (table) => [
    uniqueIndex("idx_rr_panels_message").on(table.messageId).where(sql`message_id IS NOT NULL`),
    check("reaction_role_panels_mode_check", sql`mode IN ('toggle', 'unique', 'verify')`),
  ],
);

export const memberRecords = sqliteTable(
  "member_records",
  {
    userId: text("user_id").primaryKey(),
    username: text().notNull(),
    displayName: text("display_name").notNull(),
    avatar: text(),
    joinedAt: text("joined_at"),
    rulesAcceptedAt: text("rules_accepted_at"),
    leftAt: text("left_at"),
    inGuild: integer("in_guild").default(1).notNull(),
    registerThreadId: text("register_thread_id"),
    registerSubmittedAt: text("register_submitted_at"),
    registerSubmittedName: text("register_submitted_name"),
    registerSubmittedSsoName: text("register_submitted_sso_name"),
    registerSubmittedAge: text("register_submitted_age"),
    registerStatus: text("register_status"),
    registerThreadExpiresAt: text("register_thread_expires_at"),
  },
  (table) => [
    index("idx_member_records_register_status").on(table.registerStatus),
    index("idx_member_records_in_guild").on(table.inGuild),
  ],
);

export const webSessions = sqliteTable("web_sessions", {
  id: text().primaryKey(),
  userId: text("user_id").notNull(),
  username: text().notNull(),
  avatar: text(),
  role: text().default("admin").notNull(),
  expiresAt: integer("expires_at").notNull(),
});

export const birthdayAnchorMessages = sqliteTable("birthday_anchor_messages", {
  position: integer().primaryKey(),
  messageId: text("message_id").notNull(),
  months: text().default("").notNull(),
});

export const reactionRoleMappings = sqliteTable(
  "reaction_role_mappings",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    panelId: integer("panel_id")
      .notNull()
      .references(() => reactionRolePanels.id, { onDelete: "cascade" }),
    emojiName: text("emoji_name"),
    emojiId: text("emoji_id"),
    roleIds: text("role_ids").notNull(),
    label: text(),
    position: integer().default(0).notNull(),
  },
  (table) => [uniqueIndex("idx_rr_map_emoji").on(table.panelId, table.emojiId, table.emojiName)],
);

export const events = sqliteTable(
  "events",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    messageId: text("message_id").notNull().unique(),
    channelId: text("channel_id").notNull(),
    title: text().notNull(),
    startsAt: text("starts_at").notNull(),
    endsAt: text("ends_at").notNull(),
    status: text().default("scheduled").notNull(),
    voiceChannelId: text("voice_channel_id"),
    activatedAt: text("activated_at"),
    completedAt: text("completed_at"),
    trackingIncomplete: integer("tracking_incomplete").default(0).notNull(),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
    remindedAt: text("reminded_at"),
    description: text().default("").notNull(),
    configuredVoiceChannelId: text("configured_voice_channel_id"),
    useFont: integer("use_font").default(0).notNull(),
    channelClearedAt: text("channel_cleared_at"),
  },
  (table) => [
    index("idx_events_starts_at").on(table.startsAt),
    index("idx_events_status_starts").on(table.status, table.startsAt),
  ],
);

export const eventSignups = sqliteTable(
  "event_signups",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    eventId: integer("event_id")
      .notNull()
      .references(() => events.id, { onDelete: "cascade" }),
    rawName: text("raw_name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    choice: text().notNull(),
    userId: text("user_id"),
    matchSource: text("match_source").notNull(),
    withdrawnAt: text("withdrawn_at"),
    attendanceStatus: text("attendance_status"),
    firstJoinedAt: text("first_joined_at"),
    lastLeftAt: text("last_left_at"),
    lateMinutes: integer("late_minutes"),
    earlyMinutes: integer("early_minutes"),
    // Drives the event embed's name-list ordering within each choice category: set on first
    // signup, bumped only when `choice` actually changes (see upsertSignupByUserStmt). Defaults
    // to an epoch value for rows that predate this column, so they fall back to `id` order
    // (see the ORDER BY in selectSignupsByEventStmt) until they next change their vote.
    choiceChangedAt: text("choice_changed_at").default("1970-01-01T00:00:00.000Z").notNull(),
  },
  (table) => [
    // Unnamed in the original DDL (SQLite auto-names it sqlite_autoindex_event_signups_N) — this
    // is what upsertSignupByUserStmt's ON CONFLICT(event_id, normalized_name) targets.
    unique().on(table.eventId, table.normalizedName),
    uniqueIndex("idx_event_signups_user_unique").on(table.eventId, table.userId).where(sql`user_id IS NOT NULL`),
    index("idx_event_signups_user").on(table.userId),
    index("idx_event_signups_event").on(table.eventId),
  ],
);

export const eventVoiceLog = sqliteTable(
  "event_voice_log",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    eventId: integer("event_id")
      .notNull()
      .references(() => events.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    action: text().notNull(),
    at: text().notNull(),
  },
  (table) => [index("idx_event_voice_log_event").on(table.eventId, table.userId, table.at)],
);

export const commandRegistrationState = sqliteTable(
  "command_registration_state",
  {
    id: integer().primaryKey(),
    definitionsHash: text("definitions_hash"),
  },
  () => [check("command_registration_state_id_singleton", sql`id = 1`)],
);

export const eventTemplates = sqliteTable(
  "event_templates",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    name: text().notNull(),
    defaultTitle: text("default_title").notNull(),
    baseDescription: text("base_description").default("").notNull(),
    defaultChannelId: text("default_channel_id"),
    defaultMentionRoleId: text("default_mention_role_id"),
    defaultVoiceChannelId: text("default_voice_channel_id"),
    defaultWeekday: integer("default_weekday"),
    defaultStartTime: text("default_start_time"),
    defaultEndTime: text("default_end_time"),
    useFont: integer("use_font").default(0).notNull(),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [uniqueIndex("idx_event_templates_name").on(table.name)],
);

export const dashboardAccessOverrides = sqliteTable("dashboard_access_overrides", {
  featureKey: text("feature_key").primaryKey(),
  gateJson: text("gate_json").notNull(),
});

export const dashboardAuditLog = sqliteTable(
  "dashboard_audit_log",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    at: text().notNull(),
    userId: text("user_id").notNull(),
    username: text().notNull(),
    role: text().notNull(),
    method: text().notNull(),
    path: text().notNull(),
    statusCode: integer("status_code").notNull(),
  },
  (table) => [index("idx_dashboard_audit_log_at").on(table.at)],
);

export const dashboardUserOverrides = sqliteTable(
  "dashboard_user_overrides",
  {
    userId: text("user_id").primaryKey(),
    mode: text().notNull(),
    role: text(),
    note: text(),
    setByUserId: text("set_by_user_id").notNull(),
    setByUsername: text("set_by_username").notNull(),
    setAt: text("set_at").notNull(),
  },
  () => [check("dashboard_user_overrides_mode_check", sql`mode IN ('grant', 'block')`)],
);

export const dashboardTemporaryGrants = sqliteTable(
  "dashboard_temporary_grants",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    userId: text("user_id").notNull(),
    role: text().notNull(),
    expiresAt: text("expires_at").notNull(),
    grantedByUserId: text("granted_by_user_id").notNull(),
    grantedByUsername: text("granted_by_username").notNull(),
    grantedAt: text("granted_at").notNull(),
    revokedAt: text("revoked_at"),
  },
  (table) => [index("idx_dashboard_temporary_grants_user").on(table.userId, table.expiresAt)],
);

export const dashboardApiTokens = sqliteTable("dashboard_api_tokens", {
  id: integer().primaryKey({ autoIncrement: true }),
  label: text().notNull(),
  tokenHash: text("token_hash").notNull().unique(),
  createdByUserId: text("created_by_user_id").notNull(),
  createdByUsername: text("created_by_username").notNull(),
  createdAt: text("created_at").notNull(),
  lastUsedAt: text("last_used_at"),
});

export const scheduledEventPublishes = sqliteTable(
  "scheduled_event_publishes",
  {
    id: integer().primaryKey({ autoIncrement: true }),
    publishAt: text("publish_at").notNull(),
    payload: text().notNull(),
    publishedEventId: integer("published_event_id"),
    attempts: integer().default(0).notNull(),
    lastError: text("last_error"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [index("idx_scheduled_event_publishes_due").on(table.publishAt)],
);

export const temporaryVoiceChannels = sqliteTable(
  "temporary_voice_channels",
  {
    channelId: text("channel_id").primaryKey(),
    guildId: text("guild_id").notNull(),
    eventId: integer("event_id"),
    createdAt: text("created_at").notNull(),
    createdByUserId: text("created_by_user_id").notNull(),
  },
  (table) => [index("idx_temporary_voice_channels_event").on(table.eventId)],
);
