/**
 * A curated (not exhaustive) set of standard Unicode emoji for the reaction-role
 * emoji picker, grouped by category with searchable names. Deliberately a plain
 * static array rather than an external emoji-dataset dependency — a few hundred
 * common entries covers the vast majority of reaction-role use, and custom guild
 * emoji (fetched live from the API) round out anything this list doesn't have.
 */
export interface StandardEmoji {
  char: string;
  name: string;
  category: string;
}

const RAW: Array<[string, string]> = [
  // Smileys
  ["😀", "grinning"], ["😃", "smiley"], ["😄", "smile"], ["😁", "grin"], ["😆", "laughing"],
  ["😅", "sweat smile"], ["🤣", "rofl"], ["😂", "joy"], ["🙂", "slight smile"], ["🙃", "upside down"],
  ["😉", "wink"], ["😊", "blush"], ["😇", "innocent"], ["🥰", "smiling hearts"], ["😍", "heart eyes"],
  ["🤩", "star struck"], ["😘", "kiss"], ["😗", "kissing"], ["☺️", "smiling"], ["😚", "kissing closed eyes"],
  ["😙", "kissing smiling eyes"], ["🥲", "smiling tear"], ["😋", "yum"], ["😛", "tongue"], ["😜", "wink tongue"],
  ["🤪", "zany"], ["😝", "squint tongue"], ["🤑", "money mouth"], ["🤗", "hugging"], ["🤭", "hand over mouth"],
  ["🤫", "shushing"], ["🤔", "thinking"], ["🤐", "zipper mouth"], ["🤨", "raised eyebrow"], ["😐", "neutral"],
  ["😑", "expressionless"], ["😶", "no mouth"], ["😏", "smirk"], ["😒", "unamused"], ["🙄", "eye roll"],
  ["😬", "grimacing"], ["🤥", "lying"], ["😌", "relieved"], ["😔", "pensive"], ["😪", "sleepy"],
  ["🤤", "drooling"], ["😴", "sleeping"], ["😷", "mask"], ["🤒", "thermometer"], ["🤕", "head bandage"],
  ["🤢", "nauseated"], ["🤮", "vomiting"], ["🤧", "sneezing"], ["🥵", "hot"], ["🥶", "cold"],
  ["🥴", "woozy"], ["😵", "dizzy"], ["🤯", "exploding head"], ["🤠", "cowboy"], ["🥳", "partying"],
  ["🥸", "disguised"], ["😎", "sunglasses"], ["🤓", "nerd"], ["🧐", "monocle"], ["😕", "confused"],
  ["😟", "worried"], ["🙁", "frowning"], ["☹️", "frown"], ["😮", "open mouth"], ["😯", "hushed"],
  ["😲", "astonished"], ["😳", "flushed"], ["🥺", "pleading"], ["😦", "frowning open mouth"], ["😧", "anguished"],
  ["😨", "fearful"], ["😰", "anxious sweat"], ["😥", "sad relieved"], ["😢", "cry"], ["😭", "sob"],
  ["😱", "scream"], ["😖", "confounded"], ["😣", "persevere"], ["😞", "disappointed"], ["😓", "downcast sweat"],
  ["😩", "weary"], ["😫", "tired"], ["🥱", "yawning"], ["😤", "triumph"], ["😡", "rage"],
  ["😠", "angry"], ["🤬", "cursing"], ["😈", "smiling devil"], ["👿", "angry devil"], ["💀", "skull"],
  ["☠️", "skull crossbones"], ["💩", "poop"], ["🤡", "clown"], ["👹", "ogre"], ["👺", "goblin"],
  ["👻", "ghost"], ["👽", "alien"], ["👾", "alien monster"], ["🤖", "robot"], ["😺", "cat smile"],
  // Gestures / people
  ["👋", "wave"], ["🤚", "raised back hand"], ["🖐️", "hand fingers splayed"], ["✋", "raised hand"], ["🖖", "vulcan"],
  ["👌", "ok hand"], ["🤌", "pinched fingers"], ["🤏", "pinching hand"], ["✌️", "victory"], ["🤞", "crossed fingers"],
  ["🤟", "love you gesture"], ["🤘", "rock on"], ["🤙", "call me"], ["👈", "point left"], ["👉", "point right"],
  ["👆", "point up"], ["🖕", "middle finger"], ["👇", "point down"], ["☝️", "index up"], ["👍", "thumbs up"],
  ["👎", "thumbs down"], ["✊", "fist"], ["👊", "punch"], ["🤛", "fist left"], ["🤜", "fist right"],
  ["👏", "clap"], ["🙌", "raised hands"], ["👐", "open hands"], ["🤲", "palms up"], ["🤝", "handshake"],
  ["🙏", "pray"], ["✍️", "writing hand"], ["💅", "nail polish"], ["🦶", "foot"], ["👂", "ear"],
  ["👀", "eyes"], ["👁️", "eye"], ["🧠", "brain"], ["🦷", "tooth"], ["💪", "muscle"],
  ["🫡", "salute"], ["👶", "baby"], ["🧒", "child"], ["👦", "boy"], ["👧", "girl"],
  ["🧑", "person"], ["👨", "man"], ["👩", "woman"], ["🧓", "older person"], ["👴", "old man"],
  ["👵", "old woman"], ["🤴", "prince"], ["👸", "princess"], ["🥷", "ninja"], ["🦸", "superhero"],
  ["🦹", "supervillain"], ["🧙", "mage"], ["🧚", "fairy"], ["🧛", "vampire"], ["🧟", "zombie"],
  // Hearts / symbols
  ["❤️", "red heart"], ["🧡", "orange heart"], ["💛", "yellow heart"], ["💚", "green heart"], ["💙", "blue heart"],
  ["💜", "purple heart"], ["🖤", "black heart"], ["🤍", "white heart"], ["🤎", "brown heart"], ["💔", "broken heart"],
  ["❣️", "heart exclamation"], ["💕", "two hearts"], ["💞", "revolving hearts"], ["💓", "beating heart"], ["💗", "growing heart"],
  ["💖", "sparkling heart"], ["💘", "heart arrow"], ["💝", "heart ribbon"], ["💟", "heart decoration"], ["♥️", "heart suit"],
  ["✨", "sparkles"], ["⭐", "star"], ["🌟", "glowing star"], ["💫", "dizzy star"], ["🔥", "fire"],
  ["💯", "hundred"], ["💥", "boom"], ["💢", "anger"], ["💦", "sweat drops"], ["💨", "dash"],
  ["🕳️", "hole"], ["💣", "bomb"], ["💬", "speech balloon"], ["👁️‍🗨️", "eye speech"], ["🗨️", "left speech"],
  ["🗯️", "anger balloon"], ["💭", "thought balloon"], ["💤", "zzz"], ["✅", "check mark"], ["☑️", "check box"],
  ["✔️", "heavy check"], ["❌", "cross mark"], ["❎", "cross box"], ["➕", "plus"], ["➖", "minus"],
  ["➗", "divide"], ["❓", "question"], ["❗", "exclamation"], ["⚠️", "warning"], ["🚫", "no entry"],
  ["🔞", "18+"], ["📛", "name badge"], ["💠", "diamond dot"], ["♻️", "recycle"], ["⚜️", "fleur"],
  ["🔰", "beginner"], ["♾️", "infinity"], ["🔱", "trident"], ["⭕", "circle"], ["🔴", "red circle"],
  ["🟠", "orange circle"], ["🟡", "yellow circle"], ["🟢", "green circle"], ["🔵", "blue circle"], ["🟣", "purple circle"],
  ["🟤", "brown circle"], ["⚫", "black circle"], ["⚪", "white circle"], ["🟥", "red square"], ["🟧", "orange square"],
  ["🟨", "yellow square"], ["🟩", "green square"], ["🟦", "blue square"], ["🟪", "purple square"], ["⬛", "black square"],
  ["⬜", "white square"], ["🔶", "large orange diamond"], ["🔷", "large blue diamond"], ["🔸", "small orange diamond"], ["🔹", "small blue diamond"],
  // Animals / nature
  ["🐶", "dog"], ["🐱", "cat"], ["🐭", "mouse"], ["🐹", "hamster"], ["🐰", "rabbit"],
  ["🦊", "fox"], ["🐻", "bear"], ["🐼", "panda"], ["🐨", "koala"], ["🐯", "tiger"],
  ["🦁", "lion"], ["🐮", "cow"], ["🐷", "pig"], ["🐸", "frog"], ["🐵", "monkey"],
  ["🐔", "chicken"], ["🐧", "penguin"], ["🐦", "bird"], ["🦅", "eagle"], ["🦉", "owl"],
  ["🦇", "bat"], ["🐺", "wolf"], ["🐗", "boar"], ["🐴", "horse"], ["🦄", "unicorn"],
  ["🐝", "bee"], ["🐛", "bug"], ["🦋", "butterfly"], ["🐌", "snail"], ["🐞", "ladybug"],
  ["🐜", "ant"], ["🕷️", "spider"], ["🦂", "scorpion"], ["🐢", "turtle"], ["🐍", "snake"],
  ["🦎", "lizard"], ["🦖", "trex"], ["🐙", "octopus"], ["🦑", "squid"], ["🦀", "crab"],
  ["🐬", "dolphin"], ["🐳", "whale"], ["🐟", "fish"], ["🦈", "shark"], ["🐊", "crocodile"],
  ["🐅", "tiger2"], ["🐆", "leopard"], ["🦓", "zebra"], ["🦍", "gorilla"], ["🐘", "elephant"],
  ["🦛", "hippo"], ["🦏", "rhino"], ["🐪", "camel"], ["🦒", "giraffe"], ["🐕", "dog2"],
  ["🐩", "poodle"], ["🐈", "cat2"], ["🐓", "rooster"], ["🦃", "turkey"], ["🕊️", "dove"],
  ["🐇", "rabbit2"], ["🦔", "hedgehog"], ["🐁", "mouse2"], ["🐀", "rat"], ["🐿️", "chipmunk"],
  ["🌵", "cactus"], ["🎄", "christmas tree"], ["🌲", "evergreen"], ["🌳", "tree"], ["🌴", "palm tree"],
  ["🌱", "seedling"], ["🌿", "herb"], ["☘️", "shamrock"], ["🍀", "four leaf clover"], ["🎍", "bamboo"],
  ["🎋", "tanabata"], ["🍃", "leaves"], ["🍂", "fallen leaf"], ["🍁", "maple leaf"], ["🍄", "mushroom"],
  ["🌾", "rice"], ["💐", "bouquet"], ["🌷", "tulip"], ["🌹", "rose"], ["🥀", "wilted flower"],
  ["🌺", "hibiscus"], ["🌸", "cherry blossom"], ["🌼", "blossom"], ["🌻", "sunflower"], ["🌞", "sun face"],
  ["🌝", "moon face"], ["🌛", "first quarter moon face"], ["🌜", "last quarter moon face"], ["🌚", "new moon face"], ["🌕", "full moon"],
  ["🌈", "rainbow"], ["☀️", "sun"], ["⛅", "sun cloud"], ["☁️", "cloud"], ["🌧️", "rain cloud"],
  ["⛈️", "storm"], ["🌩️", "lightning cloud"], ["❄️", "snowflake"], ["☃️", "snowman"], ["⛄", "snowman2"],
  ["🌊", "wave"], ["💧", "droplet"],
  // Food & drink
  ["🍏", "green apple"], ["🍎", "red apple"], ["🍐", "pear"], ["🍊", "orange"], ["🍋", "lemon"],
  ["🍌", "banana"], ["🍉", "watermelon"], ["🍇", "grapes"], ["🍓", "strawberry"], ["🫐", "blueberries"],
  ["🍈", "melon"], ["🍒", "cherries"], ["🍑", "peach"], ["🥭", "mango"], ["🍍", "pineapple"],
  ["🥥", "coconut"], ["🥝", "kiwi"], ["🍅", "tomato"], ["🍆", "eggplant"], ["🥑", "avocado"],
  ["🥦", "broccoli"], ["🥬", "leafy green"], ["🥒", "cucumber"], ["🌶️", "hot pepper"], ["🫑", "bell pepper"],
  ["🌽", "corn"], ["🥕", "carrot"], ["🧄", "garlic"], ["🧅", "onion"], ["🥔", "potato"],
  ["🍞", "bread"], ["🥐", "croissant"], ["🥖", "baguette"], ["🥨", "pretzel"], ["🧀", "cheese"],
  ["🥚", "egg"], ["🍳", "fried egg"], ["🧈", "butter"], ["🥞", "pancakes"], ["🧇", "waffle"],
  ["🥓", "bacon"], ["🍗", "poultry leg"], ["🍖", "meat"], ["🌭", "hotdog"], ["🍔", "burger"],
  ["🍟", "fries"], ["🍕", "pizza"], ["🥪", "sandwich"], ["🌮", "taco"], ["🌯", "burrito"],
  ["🥗", "salad"], ["🍿", "popcorn"], ["🍱", "bento"], ["🍣", "sushi"], ["🍤", "shrimp"],
  ["🍜", "ramen"], ["🍝", "spaghetti"], ["🍲", "stew"], ["🍛", "curry"], ["🍚", "rice2"],
  ["🍙", "onigiri"], ["🍘", "rice cracker"], ["🥟", "dumpling"], ["🍥", "fish cake"], ["🥠", "fortune cookie"],
  ["🍦", "soft serve"], ["🍧", "shaved ice"], ["🍨", "ice cream"], ["🍩", "donut"], ["🍪", "cookie"],
  ["🎂", "birthday cake"], ["🍰", "shortcake"], ["🧁", "cupcake"], ["🥧", "pie"], ["🍫", "chocolate"],
  ["🍬", "candy"], ["🍭", "lollipop"], ["🍮", "custard"], ["🍯", "honey"], ["☕", "coffee"],
  ["🍵", "tea"], ["🧃", "juice box"], ["🥤", "cup with straw"], ["🧋", "bubble tea"], ["🍺", "beer"],
  ["🍻", "beers"], ["🥂", "clink glasses"], ["🍷", "wine"], ["🥃", "whiskey"], ["🍸", "cocktail"],
  ["🍹", "tropical drink"], ["🍾", "champagne"], ["🧊", "ice"],
  // Activities
  ["⚽", "soccer ball"], ["🏀", "basketball"], ["🏈", "football"], ["⚾", "baseball"], ["🥎", "softball"],
  ["🎾", "tennis"], ["🏐", "volleyball"], ["🏉", "rugby"], ["🥏", "frisbee"], ["🎱", "8 ball"],
  ["🏓", "ping pong"], ["🏸", "badminton"], ["🏒", "hockey"], ["🥅", "goal net"], ["⛳", "golf"],
  ["🏹", "bow arrow"], ["🎣", "fishing pole"], ["🥊", "boxing glove"], ["🥋", "martial arts"], ["🎽", "running shirt"],
  ["🛹", "skateboard"], ["🛼", "roller skate"], ["🎿", "ski"], ["🏂", "snowboard"], ["🏆", "trophy"],
  ["🥇", "1st place"], ["🥈", "2nd place"], ["🥉", "3rd place"], ["🏅", "medal"], ["🎖️", "military medal"],
  ["🎮", "video game"], ["🕹️", "joystick"], ["🎲", "dice"], ["🧩", "puzzle piece"], ["🎯", "dart"],
  ["🎳", "bowling"], ["🎨", "art palette"], ["🎭", "performing arts"], ["🎪", "circus tent"], ["🎬", "clapper"],
  ["🎤", "microphone"], ["🎧", "headphone"], ["🎸", "guitar"], ["🎹", "piano"], ["🥁", "drum"],
  ["🎺", "trumpet"], ["🎷", "saxophone"], ["🎻", "violin"], ["🎵", "musical note"], ["🎶", "notes"],
  ["🎉", "party popper"], ["🎊", "confetti ball"], ["🎈", "balloon"], ["🎁", "gift"], ["🏵️", "rosette"],
  ["🎗️", "reminder ribbon"], ["🏆", "trophy2"],
  // Travel / objects
  ["🚗", "car"], ["🚕", "taxi"], ["🚙", "suv"], ["🚌", "bus"], ["🏎️", "race car"],
  ["🚓", "police car"], ["🚑", "ambulance"], ["🚒", "fire engine"], ["🚚", "truck"], ["🚲", "bicycle"],
  ["🛴", "scooter"], ["✈️", "airplane"], ["🚀", "rocket"], ["🛸", "ufo"], ["🚁", "helicopter"],
  ["⛵", "sailboat"], ["🚤", "speedboat"], ["🛳️", "ship"], ["⚓", "anchor"], ["🗺️", "map"],
  ["🏔️", "mountain"], ["🏕️", "camping"], ["🏖️", "beach"], ["🏝️", "island"], ["🏠", "house"],
  ["🏢", "office"], ["🏰", "castle"], ["🗼", "tower"], ["🎡", "ferris wheel"], ["🎢", "roller coaster"],
  ["💡", "bulb"], ["🔦", "flashlight"], ["🕯️", "candle"], ["📱", "phone"], ["💻", "laptop"],
  ["⌨️", "keyboard"], ["🖥️", "desktop"], ["🖨️", "printer"], ["📷", "camera"], ["🎥", "movie camera"],
  ["📺", "tv"], ["⏰", "alarm clock"], ["⌚", "watch"], ["📚", "books"], ["📖", "open book"],
  ["✏️", "pencil"], ["🖊️", "pen"], ["📌", "pushpin"], ["📎", "paperclip"], ["✂️", "scissors"],
  ["🔒", "locked"], ["🔓", "unlocked"], ["🔑", "key"], ["🔨", "hammer"], ["🛠️", "tools"],
  ["⚙️", "gear"], ["🧲", "magnet"], ["🧪", "test tube"], ["🔬", "microscope"], ["🔭", "telescope"],
  ["📡", "satellite antenna"], ["💰", "money bag"], ["💵", "dollar"], ["💳", "credit card"], ["💎", "gem"],
  ["⚖️", "balance scale"], ["🧰", "toolbox"], ["🧭", "compass"], ["⏳", "hourglass"], ["🎯", "target"],
];

export const STANDARD_EMOJI: StandardEmoji[] = RAW.map(([char, name]) => ({ char, name, category: "Emoji" }));
